name: Server Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'mcp-mongo-project/**'
      - '.github/workflows/deploy_mcp.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Private Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: ./mcp-mongo-project
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/mcpmongo-server:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_IPADDRESS }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: |
            docker stop mcpmongo-server || true
            docker rm mcpmongo-server || true

            docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

            docker pull ${{ secrets.REGISTRY_URL }}/mcpmongo-server:latest

            docker run -d \
              --name mcpmongo-server \
              -p 3001:3001 \
              -e ACCESS_KEY="${{ secrets.ACCESS_KEY }}" \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -e MONGODB_NAME="${{ secrets.MONGODB_NAME }}" \
              -e POSTGRES_URI="${{ secrets.POSTGRES_URI }}" \
              --restart unless-stopped \
              ${{ secrets.REGISTRY_URL }}/mcpmongo-server:latest