name: Defects-AI Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build server image
        uses: docker/build-push-action@v5
        with:
          context: ./mcp_mongo_postgres
          file: ./mcp_mongo_postgres/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mcpi:latest
      
      - name: Build client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/defai:latest

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_SERVER_IP }}
          username: ${{ secrets.TEST_SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /app
            echo "${{ secrets.ENV_SERVER_FILE }}" | sudo tee /app/.env_server
            echo "${{ secrets.ENV_APP_FILE }}" | sudo tee /app/.env_main

            sudo docker stop mcpi || true
            sudo docker rm mcpi || true
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mcpi:latest
            sudo docker run -d --name mcpi -p 3003:3003 --env-file /app/.env_server ${{ secrets.DOCKER_HUB_USERNAME }}/mcpi:latest

            sudo docker stop defai || true
            sudo docker rm defai || true
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/defai:latest
            sudo docker run -d --name defai -p 3002:3002 --env-file /app/.env_main ${{ secrets.DOCKER_HUB_USERNAME }}/defai:latest